namespace: 'backstage'
service:
  apiVersion: 'v1'
  name: 'backstage'
  port: '80'
  targetPort: 'http'

deployment:
  apiVersion: 'apps/v1'
  name: 'backstage'
  replicas: '1'

image:
  registry: 'localhost:5001'
  repository: 'backstage'
  tag: '0.1.0'

container:
  name: 'backstage'
  port: '7007'

secrets:
  backstage: 'backstage-secrets'
  postgres: 'postgres-secrets'
  jiraTOKEN: 'Basic c2FueWFtc2hhcm1hOEBnbWFpbC5jb206QVRBVFQzeEZmR0YwZWhRWWdVSXBfeXBtbHpOd1lJcVdqUm9vVFRyLXM5Vkpnd3lZTkhDRjFCY0I4Q1dGZXdLNDViTU5jbGtmRldmZkJFSDZtaHI2WFVlbGVka3JrNEhZSDQxYi15bnlRU2lqQm81dF9pOVd2dnlsSllWRHJENmVuU2VoTkk5Tl94X3gySTZiLUdVNEFrXzRRQU5mc2FkRkFBVHdMSER3dFJUV0VCNl9kU0Jzam9NPTJBMTZFREY1'
  ghToken: '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'
  azToken: 'm7oegymfk73u7ihruo7cnvyjjeoiivhbp5434tl6ffohdnp2so2q'
  argocdToken: 'argocd.token=token-value'
  backendUrl: 'https://sturdy-system-pjjgv9gxv975f74x9.github.dev'
  incluster:
    token: 'incluster-sa-b64-encoded-token'
  cluster1:
    url: 'https://my-k8s-cluster-ip:port'
    name: 'my-k8s-cluster'
    token: 'service-account-b64-encoded-token'

postgres:
  host: 'cG9zdGdyZXMucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw='
  port: 'NTQzMg=='
  username: 'YmFja3N0YWdl'
  password: 'aHVudGVyMg=='
