namespace: 'backstage'
service:
  apiVersion: 'v1'
  name: 'backstage'
  port: '80'
  targetPort: 'http'

deployment:
  apiVersion: 'apps/v1'
  name: 'backstage'
  replicas: '1'

image:
  registry: 'localhost:5001'
  repository: 'backstage'
  tag: '0.1.0'

container:
  name: 'backstage'
  port: '7007'

secrets:
  backstage: 'backstage-secrets'
  postgres: 'postgres-secrets'
  ghToken: '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'
  azToken: '6ylwnpjiaqbdycq775hvzpap74vpjeslk7n4qw737lgucrcnkflq'
  argocdToken: 'argocd.token=token-value'
  backendUrl: 'https://animated-telegram-wr7jqj7rpj6g35495.github.dev'
  incluster:
    token: 'incluster-sa-b64-encoded-token'
  cluster1:
    url: 'https://my-k8s-cluster-ip:port'
    name: 'my-k8s-cluster'
    token: 'service-account-b64-encoded-token'

postgres:
  host: 'cG9zdGdyZXMucG9zdGdyZXMuc3ZjLmNsdXN0ZXIubG9jYWw='
  port: 'NTQzMg=='
  username: 'YmFja3N0YWdl'
  password: 'aHVudGVyMg=='
