# kubernetes/postgres.yaml
apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        backstage.io/kubernetes-id: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: 'IfNotPresent'
          args: ["--lower_case_table_names=1","--skip-ssl","--character_set_server=utf8mb4","--explicit_defaults_for_timestamp"]
          ports:
            - containerPort: {{ .Values.container.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.mysql.secret }}