apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ALLOW_EMPTY_PASSWORD: '{{ .Values.mysql.allowEmptyPwd }}'
  MYSQL_DATABASE: {{ .Values.mysql.database }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}