# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backstage }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  GITHUB_TOKEN: {{ .Values.secrets.ghToken }}
  BACKEND_URL: {{ .Values.secrets.backendUrl }}